#
# $Author: lizhijie $
# $Id: Makefile,v 1.1.1.1 2006/11/30 17:01:32 lizhijie Exp $
#

include $(TOP_DIR)/Makefile.pre

KERNEL_LIB:= ieee80211softmac.o
	
KSRC = 	 \
	ieee80211softmac_io.c \
	ieee80211softmac_auth.c \
	ieee80211softmac_module.c \
	ieee80211softmac_scan.c \
	ieee80211softmac_wx.c \
	ieee80211softmac_assoc.c \
	ieee80211softmac_event.c
			
include $(TOP_DIR)/Makefile.post
