
objs :=as_events.o as_event_hook.o as_calling_agent.o as_callee_monitor.o \
		as_callee_agent.o as_net_agent.o as_data_sendout_agent.o

include $(USER_TOP_DIR)/Makefile.include

clear:
	$(RM) *.o *.*~ core
