#
# $Revision: 1.1.1.1 $
# $Author: lizhijie $
# $Log: Makefile,v $
# Revision 1.1.1.1  2006/11/30 16:46:14  lizhijie
# MAC VirtualMAC
#
# Revision 1.1.1.1  2006/03/06 10:17:07  lizhijie
# Virtual MAC upon 802.11
#
# Revision 1.1.1.1  2006/03/03 08:24:49  lizhijie
# softmac for wireless
#
#

include $(TOP_DIR)/Makefile.pre

KERNEL_LIB:=vnetif.o
	
KSRC = 	 \
	vnetif.c 

include $(TOP_DIR)/Makefile.post
