#
# $Revision: 1.1.1.1 $
# $Author: lizhijie $
# $Log: Makefile,v $
# Revision 1.1.1.1  2006/11/30 17:01:32  lizhijie
# MAC VMAC 2
#
# Revision 1.1.1.1  2006/04/03 02:37:52  lizhijie
# vmac for mesg
#
# Revision 1.1.1.1  2006/03/06 10:17:07  lizhijie
# Virtual MAC upon 802.11
#
# Revision 1.1.1.1  2006/03/03 08:24:49  lizhijie
# softmac for wireless
#
#

include $(TOP_DIR)/Makefile.pre

KERNEL_LIB:=vm_core.o
	
KSRC = 	 \
	core.c 

#ifeq ($(DEBUG_TIGER),yes)
#	KSRC += as_fxs_tiger.c
#endif	

include $(TOP_DIR)/Makefile.post
