#
# $Author: lizhijie $
# $Id: Makefile,v 1.1.1.1 2006/11/30 17:01:32 lizhijie Exp $
#

include $(TOP_DIR)/Makefile.pre

KERNEL_LIB:= ieee80211_crypt_ccmp.o
	
KSRC = 	 \
	ieee80211_crypt_ccmp.c 
			
include $(TOP_DIR)/Makefile.post
