#
# $Revision: 1.1.1.1 $
# $Author: lizhijie $
# $Log: Makefile,v $
# Revision 1.1.1.1  2006/11/30 16:45:28  lizhijie
# MAC SoftMAC
#
# Revision 1.1.1.1  2006/03/03 08:24:49  lizhijie
# softmac for wireless
#
#

include $(TOP_DIR)/Makefile.pre

KERNEL_LIB:=softmac_core.o
	
KSRC = 	 \
	softmac_core.c 

#ifeq ($(DEBUG_TIGER),yes)
#	KSRC += as_fxs_tiger.c
#endif	

include $(TOP_DIR)/Makefile.post
